import {CHAIN,addr,number,json,cached} from './protocol-utils.js';
export const protocols=[
 {id:'delta',name:'Delta',url:'https://deltaliquidity.app/pools'},
 {id:'fables',name:'Fables',url:'https://www.fables.fi/markets'},
 {id:'ramses',name:'Ramses',url:'https://www.ramses.xyz/'},
 {id:'longbow',name:'Longbow',url:'https://www.longbow.cash/earn'},
 {id:'pendle',name:'Pendle',url:'https://app.pendle.finance/trade/markets?chains=robinhood'},
 {id:'earn',name:'EARN',url:'https://earnonhood.com/auto'}
];
const date=v=>{const n=typeof v==='number'?v*1000:Date.parse(v);return Number.isFinite(n)?n:null;};
function market(protocol,id,name,type,extra={}){return {id:protocol+':'+id,protocol,chainId:CHAIN,name:String(name).slice(0,160),type,contract:addr(id),assets:[],rate:null,rateType:null,feeRate:null,rewardRate:null,tvlUsd:null,sourceUpdatedAt:null,estimated:false,risks:['smart-contract','liquidity'],...extra};}
async function delta(){const d=await json('https://deltaliquidity.app/api/farms/topology');if(!Array.isArray(d.farms))throw Error();return d.farms.filter(f=>addr(f.vault)&&addr(f.farm)).map(f=>market('delta',f.vault,'Delta '+f.vault.slice(0,8),'managed-liquidity',{farm:addr(f.farm),pool:addr(f.pool),assets:[addr(f.token0),addr(f.token1)].filter(Boolean),rewardToken:addr(f.rewardToken),rateBasis:'On-chain farm rates not yet valued',risks:['smart-contract','impermanent-loss','concentrated-liquidity','reward-token-volatility']}));}
async function fables(){const d=await json('https://www.fables.fi/api/indexer?op=marks');if(!Array.isArray(d.data?.Pool))throw Error();return d.data.Pool.filter(p=>/^0x[0-9a-f]{64}$/i.test(p.id)).map(p=>market('fables',p.id,'Fables '+p.id.slice(0,10),'hook-liquidity',{poolId:p.id,rateBasis:'Pool registry; APR not supplied by this source',risks:['smart-contract','hook','impermanent-loss','concentrated-liquidity']}));}
async function ramses(){const d=await json('https://gateway.kingdom.dev/robinhood/api/all-pools');if(!Array.isArray(d.pools))throw Error();return d.pools.filter(p=>addr(p.id)).map(p=>market('ramses',p.id,p.symbol,p.isCl?'concentrated-liquidity':p.isDlmm?'bin-liquidity':'liquidity',{assets:[addr(p.token0?.address),addr(p.token1?.address)].filter(Boolean),rate:number(p.lpApr),rateType:'APR',feeRate:number(p.feeApr),rewardRate:number(p.rewardApr),tvlUsd:number(p.tvlUsd),volume24hUsd:number(p.last24hVolume),gauge:addr(p.gaugeAddress),walletReceipt:!p.isCl&&!p.isDlmm,rateBasis:'Protocol-reported APR; observation window not verified',risks:['smart-contract','impermanent-loss',...(p.isCl?['concentrated-liquidity']:[]),'reward-token-volatility']}));}
async function longbow(){const d=await json('https://www.longbow.cash/api/v2/vaults');if(!Array.isArray(d.vaults))throw Error();return d.vaults.filter(v=>addr(v.address)&&!v.error).map(v=>market('longbow',v.address,v.name,'lending-vault',{assets:[addr(v.asset)].filter(Boolean),assetSymbol:v.assetSymbol,rate:number(v.apy),rateType:'APY',tvlUsd:v.assetSymbol==='USDG'?number(v.tvl):null,liquidityUnits:number(v.withdrawableNow),sourceUpdatedAt:date(d.asOf),closed:!!v.closed,rateBasis:v.apyBasis||'Protocol-reported APY',risks:['smart-contract','borrower-liquidation','oracle','withdrawal-liquidity'],underlyingProtocol:'Morpho'}));}
async function pendle(){const rows=[];for(let skip=0;skip<2000;skip+=100){const d=await json('https://api-v2.pendle.finance/core/v2/markets/all?chainId=4663&limit=100&skip='+skip);if(!Array.isArray(d.results))throw Error();rows.push(...d.results);if(rows.length>=d.total||d.results.length<100)break;if(skip===1900)throw Error('Catalog truncated');}return rows.filter(v=>Number(v.chainId)===CHAIN&&addr(v.address)).map(v=>market('pendle',v.address,v.name,'yield-liquidity',{assets:(v.inputTokens||[]).filter(a=>a.startsWith('4663-')).map(a=>addr(a.slice(5))).filter(Boolean),pt:v.pt?.startsWith('4663-')?addr(v.pt.slice(5)):null,yt:v.yt?.startsWith('4663-')?addr(v.yt.slice(5)):null,sy:v.sy?.startsWith('4663-')?addr(v.sy.slice(5)):null,rate:number(v.details?.aggregatedApy)===null?null:number(v.details.aggregatedApy)*100,rateType:'APY',fixedPtApy:number(v.details?.impliedApy)===null?null:number(v.details.impliedApy)*100,feeRate:number(v.details?.swapFeeApy)===null?null:number(v.details.swapFeeApy)*100,tvlUsd:number(v.details?.totalTvl),liquidityUsd:number(v.details?.liquidity),expiry:date(v.expiry),closed:date(v.expiry)<=Date.now(),rateBasis:'LP APY; PT implied APY separate; YT is not principal',risks:['smart-contract','underlying-asset','maturity','impermanent-loss']}));}
async function earn(){
 const [metrics,apr,pools,rewards]=await Promise.all([json('https://earnonhood.com/api/steer/metrics'),json('https://earnonhood.com/api/steer-apr').catch(()=>({})),json('https://earnonhood.com/api/omni/pools'),json('https://earnonhood.com/api/omni/rewards').catch(()=>({}))]);
 if(!Array.isArray(metrics.vaults)||!Array.isArray(pools.pools))throw Error();
 const vaults=metrics.vaults.filter(v=>addr(v.vault)).map(v=>{const a=apr.vaults?.[addr(v.vault)]||{};let fee=a.feeIndexed?number(a.feeApr):null,reward=a.rewardsIndexed?number(a.rewardsApr):null,estimated=false;
 if(reward===null&&number(a.manualRewards?.dailyRewardsUsd)>0&&v.tvlUsd>0){reward=a.manualRewards.dailyRewardsUsd*365/v.tvlUsd*100;estimated=true;}
 if(fee===null&&v.inRange===false)fee=0;
 if(fee===null&&v.inRange&&v.poolTvlUsd>0&&number(v.poolFees24hUsd)!==null&&number(a.lpFeeBps)!==null){fee=v.poolFees24hUsd/v.poolTvlUsd*(a.lpFeeBps/10000)*365*100;estimated=true;}
 return market('earn',v.vault,v.asset+' Auto vault','managed-liquidity',{vaultId:v.id,rate:fee!==null&&reward!==null?fee+reward:null,rateType:'APR',feeRate:fee,rewardRate:reward,estimated,tvlUsd:number(v.tvlUsd),sourceUpdatedAt:date(metrics.calculatedAt),rateBasis:'Net LP fees + rewards; unresolved components remain unavailable',risks:['smart-contract','impermanent-loss','concentrated-liquidity','reward-campaign','tokenized-stock']});});
 return [...vaults,...pools.pools.filter(p=>addr(p.address)).map(p=>{const r=rewards.pools?.find(r=>addr(r.address)===addr(p.address));const reward=r?.live&&(!r.endsAt||date(r.endsAt)>Date.now())?number(r.rewardsApr):null,fee=number(p.feeApr24h);return market('earn',p.address,p.name,'weighted-liquidity',{assets:(p.tokens||[]).map(t=>addr(t.address)).filter(Boolean),rate:fee!==null&&reward!==null?fee+reward:null,rateType:'APR',feeRate:fee,rewardRate:reward,tvlUsd:number(p.tvlUsd),sourceUpdatedAt:date(pools.calculatedAt),estimated:!!r?.rewardsEstimated,rewardEndsAt:date(r?.endsAt),rateBasis:'24h fee run-rate + live campaign APR',risks:['smart-contract','impermanent-loss','pool-implied-pricing','reward-campaign']});})];
}
const readers={delta,fables,ramses,longbow,pendle,earn};
export async function protocolCatalog(id){if(!readers[id])throw Error('Unknown protocol');return cached('markets:'+id,async()=>({markets:await readers[id](),fetchedAt:Date.now()}));}
export async function allCatalogs(){return Promise.all(protocols.map(async p=>{try{const data=await protocolCatalog(p.id);return {...p,status:'available',...data};}catch{return {...p,status:'unavailable',markets:[],fetchedAt:null};}}));}

