import {formatEther,formatUnits,getAddress,hexlify,toUtf8Bytes} from 'ethers';
import {PENDING_KEY,loadPending,loadHistory,settleLaunch} from './launch-session.js';
import {FACTORY,USDG,NATIVE,CHAIN_ID,readTerms,discoverPairs,pairAsset,prepareLaunch} from './pons-launch-core.js';
const $=id=>document.getElementById(id),wallets=new Map();let provider=null,account='',prepared=null,pending=null,busy=false,version=0,uploading=false,hosting=false,selectedImage=null,previewUrl='',checking=false,pollTimer=null,completed=false,currentTerms=null,availablePairs=[],uploadedLogo="",imageEpoch=0;
let storage;try{storage=window.localStorage;}catch{const mem=new Map();storage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};}
const rpc=(method,params=[])=>provider.request({method,params});
const status=text=>{$('status').textContent=text;};
function invalidate(){version++;prepared=null;$('review-panel').hidden=true;$('confirmed').checked=false;$('send').disabled=true;}
function lock(value){busy=value;$('connect').disabled=value||uploading;$('review').disabled=value||uploading||completed||!account||!!pending;$('send').disabled=value||uploading||!prepared||!$('confirmed').checked;$('wallet-choice').disabled=value||uploading;$('upload-image').disabled=value||uploading||!hosting||!account||!selectedImage;$('image-file').disabled=value||uploading;$('new-token').disabled=value||uploading;$('logo').readOnly=uploading;$('mode-url').disabled=value||uploading;$('mode-upload').disabled=value||uploading;$('pair').disabled=value||uploading||!account||!availablePairs.length;$('creator-tax').disabled=value||uploading;}
function errorText(e){if(e?.code===4001||e?.code==='ACTION_REJECTED')return 'You cancelled the wallet request. Nothing was submitted.';if(e?.code===-32002)return 'A wallet request is already open. Check your wallet extension.';if(/insufficient funds/i.test(e?.message||''))return 'Not enough ETH for the launch fee and network gas.';return e?.shortMessage||e?.message||'Request failed. Please try again.';}
function addWallet(key,name,p){if(wallets.has(key))return;wallets.set(key,p);const o=document.createElement('option');o.value=key;o.textContent=name;$('wallet-choice').append(o);}
window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.provider&&e.detail.info)addWallet(e.detail.info.uuid,e.detail.info.name,e.detail.provider);});window.dispatchEvent(new Event('eip6963:requestProvider'));
if(window.ethereum)addWallet('injected','Browser wallet',window.ethereum);
if(!wallets.size)status('Open this page in a browser with a wallet extension, or in your wallet’s browser.');
async function connect(){lock(true);invalidate();try{
 const nextProvider=wallets.get($('wallet-choice').value);if(!nextProvider)throw Error('No browser wallet found.');if(provider&&walletChanged){provider.removeListener?.('accountsChanged',walletChanged);provider.removeListener?.('chainChanged',walletChanged);}provider=nextProvider;
 const accounts=await rpc('eth_requestAccounts');if(!accounts[0])throw Error('No account selected.');
 if(Number(await rpc('eth_chainId'))!==CHAIN_ID){try{await rpc('wallet_switchEthereumChain',[{chainId:'0x1237'}]);}catch(e){if(e.code!==4902)throw e;await rpc('wallet_addEthereumChain',[{chainId:'0x1237',chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:['https://robin.etherscan.io']}]);}}
 if(Number(await rpc('eth_chainId'))!==CHAIN_ID)throw Error('Select Robinhood Chain in your wallet.');
 account=getAddress((await rpc('eth_accounts'))[0]);$('account').textContent=account;$('recipient').textContent=account.slice(0,8)+'…'+account.slice(-6);
 status('Reading current Pons launch terms…');const terms=await readTerms(rpc,account,NATIVE);currentTerms=terms;status('Checking approved paired assets…');const found=await discoverPairs(terms.read);availablePairs=found.pairs;$('pair').replaceChildren();for(const pair of availablePairs){const option=document.createElement('option');option.value=pair.address;option.textContent=pair.symbol+' · '+pair.name;$('pair').append(option);}$('pair').value=availablePairs.some(p=>p.address===USDG)?USDG:NATIVE;$('creator-tax').max=String(Math.min(terms.maxCreatorTaxBps,10000)/100);$('tax-hint').textContent='Pons currently allows 0–'+$('creator-tax').max+'%. Paid to your creator wallet.';$('pair-hint').textContent=found.failures?'Some assets could not be checked. Reconnect to retry.':'Only assets currently approved by Pons.';$('config').replaceChildren();for(const c of terms.configs){const o=document.createElement('option');o.value=c.id;o.textContent='Config '+c.id+' · '+Number(formatUnits(c.config.supply,18)).toLocaleString()+' tokens · '+Number(c.config.curveFeeBps)/100+'% protocol fee';$('config').append(o);}$('config').disabled=false;
 updateEconomics();
 walletChanged=()=>{invalidate();account='';$('account').textContent='Wallet changed. Connect again to refresh.';lock(busy);};provider.on?.('accountsChanged',walletChanged);provider.on?.('chainChanged',walletChanged);
 if(pending)await checkPending();
 }catch(e){account='';status(errorText(e));}finally{lock(false);updateUploadStatus();}}
function addRow(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('summary').append(dt,dd);}
$('connect').onclick=connect;
let walletChanged=null;
$('wallet-choice').onchange=()=>{invalidate();account='';lock(false);};
$('launch-form').addEventListener('input',invalidate);
$('launch-form').addEventListener('change',invalidate);
$('launch-form').onsubmit=async e=>{e.preventDefault();if(busy||pending||uploading||completed)return;invalidate();if(imageMode()==='upload'&&!uploadedLogo){try{await uploadImage();}catch(error){status(errorText(error));return;}}const current=version;const raw=Object.fromEntries(new FormData(e.target));raw.logo=imageMode()==='upload'?uploadedLogo:$('logo').value;lock(true);status('Checking fees and simulating the launch…');try{
 const candidate=await prepareLaunch(rpc,account,raw,$('config').value);if(current!==version)throw Error('Details changed during review. Review again.');
 prepared=candidate;$('summary').replaceChildren();for(const [label,value] of Object.entries({Name:prepared.fields.name,Symbol:prepared.fields.symbol,Description:prepared.fields.description,Image:prepared.fields.logo,Website:prepared.fields.website,Twitter:prepared.fields.twitter,'Paired asset':prepared.pair.symbol+' · '+prepared.pair.address,'Creator wallet':account,'Creator tax':prepared.taxBps/100+'%','Protocol curve fee':Number(prepared.config.curveFeeBps)/100+'%','Total curve fee':(Number(prepared.config.curveFeeBps)+prepared.taxBps)/100+'%','Pool fee after graduation':Number(prepared.config.poolFee)/10000+'%','Launch fee':formatEther(prepared.terms.fee)+' ETH + network gas','Estimated gas units':BigInt(prepared.gas).toString(),'Initial purchase':'0 '+prepared.pair.symbol,Buybacks:'Off',Factory:FACTORY,'Expected token':prepared.token}))addRow(label,value);
 $('review-panel').hidden=false;$('review-panel').scrollIntoView({behavior:'smooth'});status('Simulation passed. Review the details before confirming.');
 }catch(e){invalidate();status(errorText(e));}finally{lock(false);}};
$('confirmed').onchange=()=>{$('send').disabled=busy||!prepared||!$('confirmed').checked;};
function resultLink(parent,url,text){const a=document.createElement('a');a.href=url;a.textContent=text;a.target='_blank';a.rel='noopener noreferrer';parent.replaceChildren(a);}
function showPending(){if(!pending)return;$('result').hidden=false;resultLink($('transaction'),'https://robin.etherscan.io/tx/'+pending.hash,pending.hash);}
$('send').onclick=async()=>{if(busy||!prepared||pending||!$('confirmed').checked)return;const p=prepared;lock(true);try{
 if(Date.now()-p.createdAt>180000)throw Error('Review expired. Review the current terms again.');
 if(Number(await rpc('eth_chainId'))!==CHAIN_ID||getAddress((await rpc('eth_accounts'))[0])!==p.account)throw Error('Wallet or network changed. Review again.');
 const terms=await readTerms(rpc,p.account,p.pair.address);if(terms.fee!==p.terms.fee||(await terms.read('previewLaunchEconomics',[p.configId,p.pair.address]))[0]!==p.pin)throw Error('Pons terms changed. Review again.');
 await rpc('eth_call',[p.tx,'latest']);await rpc('eth_estimateGas',[p.tx]);
 if(prepared!==p||getAddress((await rpc('eth_accounts'))[0])!==p.account||Number(await rpc('eth_chainId'))!==CHAIN_ID)throw Error('Details, wallet or network changed. Review again.');
 status('Confirm the launch in your wallet.');
 const hash=await rpc('eth_sendTransaction',[p.tx]);pending={hash,account:p.account,token:p.token,name:p.fields.name,symbol:p.fields.symbol,submittedAt:Date.now()};try{storage.setItem(PENDING_KEY,JSON.stringify(pending));}catch{}invalidate();showPending();status('Transaction submitted. Waiting for confirmation…');scheduleCheck();
 }catch(e){invalidate();status(errorText(e));}finally{lock(false);}};
function renderHistory(){const history=loadHistory(storage);$('launch-history').hidden=!history.length;$('history-list').replaceChildren();for(const item of history){const row=document.createElement('article'),label=document.createElement('span'),links=document.createElement('span');label.textContent=(item.name||item.token.slice(0,8)+'…'+item.token.slice(-6))+(item.symbol?' · '+item.symbol:'')+' · '+(item.state==='confirmed'?'Launched':'Failed');resultLink(links,item.state==='confirmed'?'https://www.ponsfamily.com/launchpad/'+item.token:'https://robin.etherscan.io/tx/'+item.hash,item.state==='confirmed'?'View token ↗':'View transaction ↗');row.append(label,links);$('history-list').append(row);}}
async function receipt(hash){const r=await fetch('/api/rpc',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({method:'eth_getTransactionReceipt',params:[hash]}),signal:AbortSignal.timeout(20000)});const body=await r.json();if(!r.ok||body.error)throw Error('Could not check confirmation. Your submitted transaction is saved. Try again.');return body.result;}
function scheduleCheck(){clearTimeout(pollTimer);if(pending)pollTimer=setTimeout(()=>checkPending(),10000);}
async function checkPending(){if(!pending||checking)return;checking=true;$('check-tx').disabled=true;const current=pending;try{const r=await receipt(current.hash);if(!r){status('Transaction is still pending. You can leave this page and return later.');return;}let entry;try{entry=settleLaunch(storage,current,r);}catch{const memory={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};entry=settleLaunch(memory,current,r);try{storage.removeItem(PENDING_KEY);}catch{}}if(!entry)return;pending=null;completed=true;clearTimeout(pollTimer);invalidate();$('check-tx').hidden=true;$('new-token').hidden=false;$('result-title').textContent=entry.state==='confirmed'?'Token launched':'Launch failed';if(entry.state==='confirmed'){resultLink($('token-result'),'https://www.ponsfamily.com/launchpad/'+entry.token,'Open token on Pons ↗');status('Token launched successfully. Choose “Create another token” to start a fresh launch.');}else{status('Transaction reverted. No token was created. You can start a fresh launch.');}renderHistory();lock(busy);}catch(e){status(errorText(e));}finally{checking=false;$('check-tx').disabled=false;scheduleCheck();}}
$('check-tx').onclick=()=>checkPending();
$('new-token').onclick=()=>{if(pending||busy||uploading)return;invalidate();completed=false;const config=$('config').value,pair=$('pair').value,tax=$('creator-tax').value;$('launch-form').reset();$('config').value=config;$('pair').value=pair;$('creator-tax').value=tax;selectedImage=null;uploadedLogo='';imageEpoch++;applyImageMode(hosting?'upload':'url');updateEconomics();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';$('image-preview').hidden=true;$('result').hidden=true;$('token-result').replaceChildren();$('transaction').replaceChildren();$('result-title').textContent='Launch transaction';$('check-tx').hidden=false;$('new-token').hidden=true;updateUploadStatus();status(account?'Ready for a new token. Enter fresh token details and review the launch.':'Connect your wallet to create your next token.');lock(false);$('launch-form').scrollIntoView({behavior:'smooth'});$('launch-form').elements.name.focus();};
function updateEconomics(){
 const pair=availablePairs.find(p=>p.address===$('pair').value);if(!pair||!currentTerms)return;
 const config=currentTerms.configs.find(c=>String(c.id)===$('config').value);const threshold=pair.address===NATIVE?config?.config.graduationThreshold:pair.threshold;
 $('pair-summary').textContent=pair.symbol;$('tax-summary').textContent=$('creator-tax').value+'%';$('buy-summary').textContent='0 '+pair.symbol;
 if(threshold!==undefined)status('Graduation threshold: '+formatUnits(threshold,pair.decimals)+' '+pair.symbol+'. Launch fee: '+formatEther(currentTerms.fee)+' ETH + gas.');
}
$('pair').onchange=updateEconomics;$('config').onchange=updateEconomics;$('creator-tax').oninput=updateEconomics;
function imageMode(){return $('mode-upload').checked?'upload':'url';}
function applyImageMode(mode){$('mode-upload').checked=mode==='upload';$('mode-url').checked=mode==='url';$('upload-panel').hidden=mode!=='upload';$('url-panel').hidden=mode!=='url';$('logo').required=mode==='url';$('logo').disabled=mode!=='url';invalidate();updateUploadStatus();}
$('mode-upload').onchange=()=>applyImageMode('upload');$('mode-url').onchange=()=>applyImageMode('url');
function updateUploadStatus(){ $('upload-status').textContent=uploadedLogo?'Image uploaded and ready. No URL is needed.':hosting?(account?'Choose an image to upload. Your wallet will approve a message, without gas.':'Connect your wallet, then choose an image.'):'Image hosting is not active yet. Switch to Use image URL for now.';}
fetch('/api/launch-image').then(r=>r.json()).then(data=>{hosting=data.enabled===true;if(hosting&&!$('logo').value&&!selectedImage)applyImageMode('upload');updateUploadStatus();lock(busy);}).catch(()=>{hosting=false;updateUploadStatus();});
$('image-file').onchange=async()=>{invalidate();uploadedLogo='';selectedImage=null;const epoch=++imageEpoch;if(previewUrl)URL.revokeObjectURL(previewUrl);$('image-preview').hidden=true;const file=$('image-file').files[0];if(!file){lock(busy);return;}if(!['image/png','image/jpeg','image/webp'].includes(file.type)||!file.size||file.size>1048576){$('upload-status').textContent='Choose a PNG, JPEG or WebP image up to 1 MB.';lock(busy);return;}try{const bitmap=await createImageBitmap(file);bitmap.close();if(epoch!==imageEpoch)return;selectedImage=file;previewUrl=URL.createObjectURL(file);$('image-preview').src=previewUrl;$('image-preview').hidden=false;updateUploadStatus();if(hosting&&account)await uploadImage();}catch(e){$('upload-status').textContent=errorText(e);}lock(busy);};
async function uploadImage(){
 if(!hosting)throw Error('Image hosting is not active yet. Choose Use image URL.');if(!selectedImage)throw Error('Choose an image first.');if(!account)throw Error('Connect your wallet to upload an image.');if(busy||uploading)throw Error('An upload or wallet request is already in progress.');
 const file=selectedImage,signer=account;invalidate();uploading=true;lock(false);$('upload-status').textContent='Approve the image upload in your wallet. No gas is required.';
 try{const bytes=new Uint8Array(await file.arrayBuffer()),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join(''),timestamp=Date.now();const message=`Robinfolio token image upload\nImage SHA-256: ${hash}\nTimestamp: ${timestamp}\nThis signature only authorizes hosting this image. No transaction or spending.`;const signature=await rpc('personal_sign',[hexlify(toUtf8Bytes(message)),signer]);if(account!==signer)throw Error('Wallet changed. Upload again.');$('upload-status').textContent='Uploading image…';let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const response=await fetch('/api/launch-image',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:btoa(binary),timestamp,signature}),signal:AbortSignal.timeout(60000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Upload failed.');if(!/^https:\/\//.test(result.url))throw Error('The host did not return a public image URL.');uploadedLogo=result.url;invalidate();updateUploadStatus();}
 catch(e){$('upload-status').textContent=errorText(e);throw e;}finally{uploading=false;lock(false);}
}
$('upload-image').onclick=()=>uploadImage().catch(()=>{});
applyImageMode('url');
pending=loadPending(storage);renderHistory();if(pending){showPending();status('Checking your previous launch…');checkPending();}
